var productData = {
	arbitCons:{
		name:"任性花",
		imageURL:'../../images/product_bg1.jpg',
		producrInfo:'<div class="centits"><span class="lineCla"></span><h6 class="title_h6 font12">适合人群</h6><div><li style="list-style-type:disc;color: #8f8f94;">20-60周岁，中国大陆境内人士。</li></div></div><div class="centits"><span class="lineCla"></span><h6 class="title_h6 font12">借款用途</h6><div><li style="list-style-type:disc;color: #8f8f94;">消费用途（装修、婚礼、旅游等）、学习（出国留学等）</li></div></div><div class="centits"><span class="lineCla"></span><h6 class="title_h6 font12">额&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;度:<span style="padding-left: 5px;">最高30万</span></h6></div><div class="centits"><span class="lineCla"></span><h6 class="title_h6 font12">贷款期限:<span style="padding-left: 5px;">3年</span></h6></div><div class="centits"><span class="lineCla"></span><h6 class="title_h6 font12">年化利率:<span style="color: #FFCC33;padding-left: 5px;">7%</span></h6></div><div class="centits"><span class="lineCla"></span><h6 class="title_h6 font12">产品服务费:<span style="padding-left: 5px;">一次性扣7.5%</span></h6></div><div class="centits"><span class="lineCla"></span><span class="font12">还款方式:<span style="width: 80%;float: right">先息后本、随借随还、按日计息、按月归还、一年一归本</span></span></div>',
		applicCond:'<div class="centits"><span class="lineCla"></span><h6 class="title_h6 font12">条件</h6><ul style="padding-top: 20px; padding-left: 30px;"><li style="list-style-type:disc;color: #8f8f94;">征信情况良好，有稳定的居住场所、工作/企业经营的有房一族</li><li style="list-style-type:disc;color: #8f8f94;margin-top: 10px;">北京行政区域内有稳定工作</li><li style="list-style-type:disc;color: #8f8f94;margin-top: 10px;">北京区域内有两套及以上房产</li><li style="list-style-type:disc;color: #8f8f94;margin-top: 10px;">近一年不能连三累六，不能当前逾期</li><li style="list-style-type:disc;color: #8f8f94;margin-top: 10px;">家庭负债比<70%</address></li></ul></div>',
		ApplicProcess:'<div class="cent_tite"><div class="progress_box"><h6 class="title_h6 font12 ml10 mt15 mb15">申请流程</h6><ul class="clearfix"><li><i class="circle"></i>录入客户<em class="progress_line"></em></li><li><i class="circle"></i>准入初评<em class="progress_line"></em></li><li><i class="circle"></i>面审预约<em class="progress_line"></em></li><li><i class="circle"></i>面签放款</li></ul></div></div></div>'
	},
	arbitSta:{
		name:"任分期",
		imageURL:'../../images/product_bg2.jpg',
		producrInfo:'<div class="centits"><span class="lineCla"></span><h6 class="title_h6 font12">适合人群</h6><div><li style="list-style-type:disc;color: #8f8f94;">20-60周岁，中国大陆境内人士。</li></div></div><div class="centits"><span class="lineCla"></span><h6 class="title_h6 font12">借款用途</h6><div><li style="list-style-type:disc;color: #8f8f94;">消费用途（装修、婚礼、旅游等）、学习（出国留学等）</li></div></div><div class="centits"><span class="lineCla"></span><h6 class="title_h6 font12">额&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;度:<span style="padding-left: 5px;">最高30万</span></h6></div><div class="centits"><span class="lineCla"></span><h6 class="title_h6 font12">贷款期限:<span style="padding-left: 5px;">3年</span></h6></div><div class="centits"><span class="lineCla"></span><h6 class="title_h6 font12">年化利率:<span style="color: #FFCC33;padding-left: 5px;">7%</span></h6></div><div class="centits"><span class="lineCla"></span><h6 class="title_h6 font12">产品服务费:<span style="padding-left: 5px;">一次性扣7.4%</span></h6></div><div class="centits"><span class="lineCla"></span><span class="font12">还款方式:<span style="width: 80%;float: right">36期分期</span></span></div>',
		applicCond:'<div class="centits"><span class="lineCla"></span><h6 class="title_h6 font12">条件</h6><ul style="padding-top: 20px; padding-left: 30px;"><li style="list-style-type:disc;color: #8f8f94;">征信情况良好，有稳定的居住场所、工作/企业经营的有房一族</li><li style="list-style-type:disc;color: #8f8f94;margin-top: 10px;">北京行政区域内有稳定工作</li><li style="list-style-type:disc;color: #8f8f94;margin-top: 10px;">北京区域内有两套及以上房产</li><li style="list-style-type:disc;color: #8f8f94;margin-top: 10px;">近一年不能连三累六，不能当前逾期</li><li style="list-style-type:disc;color: #8f8f94;margin-top: 10px;">家庭负债比<70%</address></li></ul></div>',
		ApplicProcess:'<div class="cent_tite"><div class="progress_box"><h6 class="title_h6 font12 ml10 mt15 mb15">申请流程</h6><ul class="clearfix"><li><i class="circle"></i>录入客户<em class="progress_line"></em></li><li><i class="circle"></i>准入初评<em class="progress_line"></em></li><li><i class="circle"></i>面审预约<em class="progress_line"></em></li><li><i class="circle"></i>面签放款</li></ul></div></div></div>'
	}
}
